---
title: "TFEA_ChIP_Markdown_6_16_2022"
author: "Ryan Brownlee"
date: '2022-06-16'
output: html_document
---

Libraries
```{r}
library(TFEA.ChIP) #Recall TFEA.ChIP package
READY_TFEA_DATASET_TABLE <- preprocessInputData(READY_TFEA_DATASET)
```

rewad in data
```{r}
READY_TFEA_DATASET_orig <- read.csv(file = "/Users/mattr/Documents/Lasseigne_Lab_KURE/FULL_TFEA_DATASET.csv")
```

```{r}
#geneIDintoentrezID
Genes.Upreg <- Select_genes( READY_TFEA_DATASET_TABLE, min_LFC = 1) #extract vector with names of upregulated genes
Genes.Control <- Select_genes(READY_TFEA_DATASET_TABLE, min_pval = 0.5, max_pval = 1, min_LFC = -0.25, max_LFC = 0.25)
#extract vector with names of non-responsive genes
CM_list_UP <- contingency_matrix(Genes.Upreg, Genes.Control)
#generates list of contingency tables, one per dataset
pval_mat_UP <- getCMstats(CM_list_UP)
#generates list of p-values
chip_index <- get_chip_index(encodeFilter = TRUE) #select ENCODE datasets only
CM_list_UPe <- contingency_matrix(Genes.Upreg, Genes.Control, chip_index)
#generates a list of contingency tables
pval_mat_UPe <- getCMstats(CM_list_UPe, chip_index)
#Generates a list of p-values and ORs
TF_ranking <- rankTFs(pval_mat_UP, rankMethod = "gsea", makePlot = TRUE)
#ranks the transcription factors for graphing
TF_ranking[["TFranking_plot"]]
#Displays plot of TF ranking and enrichment scores
plot_CM(pval_mat_UP)
#plot p-values against ORs
chip_index <- get_chip_index(encodeFilter = TRUE)
#creates chip index of only ENCODE dataset
GSEA_run(!is.na(READY_TFEA_DATASET$Genes), !is.na(READY_TFEA_DATASET$log2FoldChange), chip_index, get.RES = TRUE)
# run GSEA analysis
```